-- MySQL Script generated by MySQL Workbench
-- Fri Oct 12 06:11:01 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema idr_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `idr_db` ;

-- -----------------------------------------------------
-- Schema idr_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `idr_db` ;
USE `idr_db` ;

-- -----------------------------------------------------
-- Table `idr_db`.`ComponentFund`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idr_db`.`ComponentFund` ;

CREATE TABLE IF NOT EXISTS `idr_db`.`ComponentFund` (
  `CFID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`CFID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `idr_db`.`Quarter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idr_db`.`Quarter` ;

CREATE TABLE IF NOT EXISTS `idr_db`.`Quarter` (
  `QuarterID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`QuarterID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `idr_db`.`FundLevelNAV`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idr_db`.`FundLevelNAV` ;

CREATE TABLE IF NOT EXISTS `idr_db`.`FundLevelNAV` (
  `PKID` INT NOT NULL,
  `CFID` INT NOT NULL,
  `QuarterID` INT NOT NULL,
  `FieldName` VARCHAR(100) NULL,
  `Value` DECIMAL(30,3) NULL,
  PRIMARY KEY (`PKID`),
  INDEX `cfid_idx` (`CFID` ASC) VISIBLE,
  INDEX `quarterid_idx` (`QuarterID` ASC) VISIBLE,
  CONSTRAINT `cfidfundlevelnav`
    FOREIGN KEY (`CFID`)
    REFERENCES `idr_db`.`ComponentFund` (`CFID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `quarteridfundlevelnav`
    FOREIGN KEY (`QuarterID`)
    REFERENCES `idr_db`.`Quarter` (`QuarterID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `idr_db`.`DiversificationNAV`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idr_db`.`DiversificationNAV` ;

CREATE TABLE IF NOT EXISTS `idr_db`.`DiversificationNAV` (
  `PKID` INT NOT NULL,
  `CFID` INT NOT NULL,
  `QuarterID` INT NOT NULL,
  `FieldName` VARCHAR(100) NULL,
  `Totalpc` DECIMAL(30,3) NULL,
  `Totalamt` DECIMAL(30,3) NULL,
  `office` DECIMAL(30,3) NULL,
  `multifamily` DECIMAL(30,3) NULL,
  `industrial` DECIMAL(30,3) NULL,
  `retail` DECIMAL(30,3) NULL,
  `hotel` DECIMAL(30,3) NULL,
  `healthcare` DECIMAL(30,3) NULL,
  `storage` DECIMAL(30,3) NULL,
  `studenthousing` DECIMAL(30,3) NULL,
  `seniorliving` DECIMAL(30,3) NULL,
  `parking` DECIMAL(30,3) NULL,
  `land` DECIMAL(30,3) NULL,
  `other` DECIMAL(30,3) NULL,
  PRIMARY KEY (`PKID`),
  INDEX `quarterid_idx` (`QuarterID` ASC) VISIBLE,
  INDEX `cfid_idx` (`CFID` ASC) VISIBLE,
  CONSTRAINT `cfiddiversificationnav`
    FOREIGN KEY (`CFID`)
    REFERENCES `idr_db`.`ComponentFund` (`CFID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `quarteriddiversificationnav`
    FOREIGN KEY (`QuarterID`)
    REFERENCES `idr_db`.`Quarter` (`QuarterID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `idr_db`.`Portfolio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idr_db`.`Portfolio` ;

CREATE TABLE IF NOT EXISTS `idr_db`.`Portfolio` (
  `PKID` INT NOT NULL,
  `CFID` INT NOT NULL,
  `QuarterID` INT NOT NULL,
  `InvestmentName` VARCHAR(45) NULL,
  `Streetaddress` VARCHAR(45) NULL,
  `msa` VARCHAR(1000) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(50) NULL,
  `zipcode` VARCHAR(50) NULL,
  `size` DECIMAL(30,3) NULL,
  `propertytype` VARCHAR(50) NULL,
  `acquisitiondate` VARCHAR(50) NULL,
  `propertylifecycle` VARCHAR(100) NULL,
  `occupancy` DECIMAL(30,3) NULL,
  `totalcostbasisamt` DECIMAL(30,3) NULL,
  `totalgavamt` DECIMAL(30,3) NULL,
  `totaldebtamt` DECIMAL(30,3) NULL,
  `totalnav` DECIMAL(30,3) NULL,
  `total1yrgoingfwdnoi` DECIMAL(30,3) NULL,
  `currentcapratepc` DECIMAL(30,3) NULL,
  `ownershippc` DECIMAL(30,3) NULL,
  `fundgav` DECIMAL(30,3) NULL,
  `funddebt` DECIMAL(30,3) NULL,
  `fundnav` DECIMAL(30,3) NULL,
  `stabilizedvalue` DECIMAL(30,3) NULL,
  PRIMARY KEY (`PKID`),
  INDEX `cfid_idx` (`CFID` ASC) VISIBLE,
  INDEX `quarterid_idx` (`QuarterID` ASC) VISIBLE,
  CONSTRAINT `cfidportfolio`
    FOREIGN KEY (`CFID`)
    REFERENCES `idr_db`.`ComponentFund` (`CFID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `quarteridportfolio`
    FOREIGN KEY (`QuarterID`)
    REFERENCES `idr_db`.`Quarter` (`QuarterID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `idr_db`.`Acquisitions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idr_db`.`Acquisitions` ;

CREATE TABLE IF NOT EXISTS `idr_db`.`Acquisitions` (
  `PKID` INT NOT NULL,
  `CFID` INT NOT NULL,
  `QuarterID` INT NOT NULL,
  `InvestmentName` VARCHAR(45) NULL,
  `Streetaddress` VARCHAR(45) NULL,
  `msa` VARCHAR(1000) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(50) NULL,
  `zipcode` VARCHAR(50) NULL,
  `size` DECIMAL(30,3) NULL,
  `propertytype` VARCHAR(50) NULL,
  `acquisitiondate` VARCHAR(50) NULL,
  `propertylifecycle` VARCHAR(100) NULL,
  `occupancy` DECIMAL(30,3) NULL,
  `totalacquicostamt` DECIMAL(30,3) NULL,
  `totalequityamt` DECIMAL(30,3) NULL,
  `totaldebtamt` DECIMAL(30,3) NULL,
  `entrycapratepc` DECIMAL(30,3) NULL,
  `total1yrgoingfwdnoi` DECIMAL(30,3) NULL,
  `fundownershippc` DECIMAL(30,3) NULL,
  `proformairr` DECIMAL(30,3) NULL,
  `proformamultiple` DECIMAL(30,3) NULL,
  PRIMARY KEY (`PKID`),
  INDEX `cfid_idx` (`CFID` ASC) VISIBLE,
  INDEX `quarterid_idx` (`QuarterID` ASC) VISIBLE,
  CONSTRAINT `cfidaquistions`
    FOREIGN KEY (`CFID`)
    REFERENCES `idr_db`.`ComponentFund` (`CFID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `quarteridacquistions`
    FOREIGN KEY (`QuarterID`)
    REFERENCES `idr_db`.`Quarter` (`QuarterID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `idr_db`.`Dispositions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idr_db`.`Dispositions` ;

CREATE TABLE IF NOT EXISTS `idr_db`.`Dispositions` (
  `PKID` INT NOT NULL,
  `CFID` INT NOT NULL,
  `QuarterID` INT NOT NULL,
  `InvestmentName` VARCHAR(45) NULL,
  `Streetaddress` VARCHAR(45) NULL,
  `msa` VARCHAR(1000) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(50) NULL,
  `zipcode` VARCHAR(50) NULL,
  `size` DECIMAL(30,3) NULL,
  `propertytype` VARCHAR(50) NULL,
  `acquisitiondate` VARCHAR(50) NULL,
  `dispositiondate` VARCHAR(50) NULL,
  `holdingperiod` DECIMAL(30,3) NULL,
  `propertylifecycle` VARCHAR(50) NULL,
  `occupancy` DECIMAL(30,3) NULL,
  `totalcostbasisamt` DECIMAL(30,3) NULL,
  `totalsalepriceamt` DECIMAL(30,3) NULL,
  `previousquartergav` DECIMAL(30,3) NULL,
  `totalrealizedproceedsamt` DECIMAL(30,3) NULL,
  `netrealizedproceedsamt` DECIMAL(30,3) NULL,
  `exitcapratepc` DECIMAL(30,3) NULL,
  `realizedgrossirrpc` DECIMAL(30,3) NULL,
  `realizedmultiple` DECIMAL(30,3) NULL,
  PRIMARY KEY (`PKID`),
  INDEX `cfid_idx` (`CFID` ASC) VISIBLE,
  INDEX `quarterid_idx` (`QuarterID` ASC) VISIBLE,
  CONSTRAINT `cfiddispositions`
    FOREIGN KEY (`CFID`)
    REFERENCES `idr_db`.`ComponentFund` (`CFID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `quarteriddispositions`
    FOREIGN KEY (`QuarterID`)
    REFERENCES `idr_db`.`Quarter` (`QuarterID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `idr_db`.`Performance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idr_db`.`Performance` ;

CREATE TABLE IF NOT EXISTS `idr_db`.`Performance` (
  `PKID` INT NOT NULL,
  `CFID` INT NOT NULL,
  `QuarterID` INT NOT NULL,
  `Timeweightedreturns` VARCHAR(100) NULL,
  `qtr` DECIMAL(30,3) NULL,
  `1year` DECIMAL(30,3) NULL,
  `3year` DECIMAL(30,3) NULL,
  `5year` DECIMAL(30,3) NULL,
  `7year` DECIMAL(30,3) NULL,
  `10year` DECIMAL(30,3) NULL,
  `sinceinception` DECIMAL(30,3) NULL,
  PRIMARY KEY (`PKID`),
  INDEX `cfid_idx` (`CFID` ASC) VISIBLE,
  INDEX `quarterid_idx` (`QuarterID` ASC) VISIBLE,
  CONSTRAINT `cfidperformance`
    FOREIGN KEY (`CFID`)
    REFERENCES `idr_db`.`ComponentFund` (`CFID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `quarteridperformance`
    FOREIGN KEY (`QuarterID`)
    REFERENCES `idr_db`.`Quarter` (`QuarterID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `idr_db`.`IDRQuarterlyInputs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idr_db`.`IDRQuarterlyInputs` ;

CREATE TABLE IF NOT EXISTS `idr_db`.`IDRQuarterlyInputs` (
  `PKID` INT NOT NULL,
  `CFID` INT NOT NULL,
  `QuarterID` INT NOT NULL,
  `NetAssetValue` DECIMAL(30,3) NULL,
  `CorePropIndexMasterFund` DECIMAL(30,3) NULL,
  `CorePropIndexFundLLC` DECIMAL(30,3) NULL,
  `CorePropIndexTrust` DECIMAL(30,3) NULL,
  PRIMARY KEY (`PKID`),
  INDEX `cfid_idx` (`CFID` ASC) VISIBLE,
  INDEX `quarterid_idx` (`QuarterID` ASC) VISIBLE,
  CONSTRAINT `cfididrquarterlyinputs`
    FOREIGN KEY (`CFID`)
    REFERENCES `idr_db`.`ComponentFund` (`CFID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `quarterididrquarterlyinputs`
    FOREIGN KEY (`QuarterID`)
    REFERENCES `idr_db`.`Quarter` (`QuarterID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `idr_db`.`Disclosures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idr_db`.`Disclosures` ;

CREATE TABLE IF NOT EXISTS `idr_db`.`Disclosures` (
  `PKID` INT NOT NULL,
  `CFID` INT NOT NULL,
  `QuarterID` INT NOT NULL,
  `Keypersonnelhired` VARCHAR(100) NULL,
  `Keypersonneldeparted` VARCHAR(100) NULL,
  `investmentguidelines` VARCHAR(100) NULL,
  `nfiodceguidelines` VARCHAR(100) NULL,
  `litigation` VARCHAR(100) NULL,
  `otherevents` VARCHAR(100) NULL,
  `descriptiondispositions` VARCHAR(100) NULL,
  `descriptionacquisitions` VARCHAR(500) NULL,
  PRIMARY KEY (`PKID`),
  INDEX `cfid_idx` (`CFID` ASC) VISIBLE,
  INDEX `quarterid_idx` (`QuarterID` ASC) VISIBLE,
  CONSTRAINT `cfiddisclosures`
    FOREIGN KEY (`CFID`)
    REFERENCES `idr_db`.`ComponentFund` (`CFID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `quarteriddisclosures`
    FOREIGN KEY (`QuarterID`)
    REFERENCES `idr_db`.`Quarter` (`QuarterID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `idr_db`.`IDRIpNFIODCE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idr_db`.`IDRIpNFIODCE` ;

CREATE TABLE IF NOT EXISTS `idr_db`.`IDRIpNFIODCE` (
  `PKID` INT NOT NULL,
  `CFID` INT NOT NULL,
  `QuarterID` INT NOT NULL,
  `FieldName` VARCHAR(100) NULL,
  `ValueType1` DECIMAL(30,3) NULL,
  `ValueType2` DECIMAL(30,3) NULL,
  PRIMARY KEY (`PKID`),
  INDEX `cfididripnfiodce_idx` (`CFID` ASC) VISIBLE,
  INDEX `quarterididriptnfiodce_idx` (`QuarterID` ASC) VISIBLE,
  CONSTRAINT `cfididripnfiodce`
    FOREIGN KEY (`CFID`)
    REFERENCES `idr_db`.`ComponentFund` (`CFID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `quarterididriptnfiodce`
    FOREIGN KEY (`QuarterID`)
    REFERENCES `idr_db`.`Quarter` (`QuarterID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `idr_db`.`IDRIpNFIODCEX`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idr_db`.`IDRIpNFIODCEX` ;

CREATE TABLE IF NOT EXISTS `idr_db`.`IDRIpNFIODCEX` (
  `PKID` INT NOT NULL,
  `CFID` INT NOT NULL,
  `QuarterID` INT NOT NULL,
  `FieldName` VARCHAR(100) NULL,
  `ValueType1` DECIMAL(30,3) NULL,
  `ValueType2` DECIMAL(30,3) NULL,
  PRIMARY KEY (`PKID`),
  INDEX `cfididripnfiodce_idx` (`CFID` ASC) VISIBLE,
  INDEX `quarterididriptnfiodce_idx` (`QuarterID` ASC) VISIBLE,
  CONSTRAINT `cfididripnfiodcex`
    FOREIGN KEY (`CFID`)
    REFERENCES `idr_db`.`ComponentFund` (`CFID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `quarterididriptnfiodcex`
    FOREIGN KEY (`QuarterID`)
    REFERENCES `idr_db`.`Quarter` (`QuarterID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `idr_db`.`OutputIDR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idr_db`.`OutputIDR` ;

CREATE TABLE IF NOT EXISTS `idr_db`.`OutputIDR` (
  `PKID` INT NOT NULL,
  `CFID` INT NOT NULL,
  `QuarterID` INT NOT NULL,
  `FieldName` VARCHAR(100) NULL,
  `ValueType1` DECIMAL(30,10) NULL,
  `ValueType2` DECIMAL(30,10) NULL,
  PRIMARY KEY (`PKID`),
  INDEX `cfididripnfiodce_idx` (`CFID` ASC) VISIBLE,
  INDEX `quarterididriptnfiodce_idx` (`QuarterID` ASC) VISIBLE,
  CONSTRAINT `cfidoutputidr`
    FOREIGN KEY (`CFID`)
    REFERENCES `idr_db`.`ComponentFund` (`CFID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `quarteridoutputidr`
    FOREIGN KEY (`QuarterID`)
    REFERENCES `idr_db`.`Quarter` (`QuarterID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `idr_db`.`OutputComponent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idr_db`.`OutputComponent` ;

CREATE TABLE IF NOT EXISTS `idr_db`.`OutputComponent` (
  `PKID` INT NOT NULL,
  `CFID` INT NOT NULL,
  `QuarterID` INT NOT NULL,
  `FieldName` VARCHAR(100) NULL,
  `ValueType1` DECIMAL(30,10) NULL,
  `ValueType2` DECIMAL(30,10) NULL,
  PRIMARY KEY (`PKID`),
  INDEX `cfididripnfiodce_idx` (`CFID` ASC) VISIBLE,
  INDEX `quarterididriptnfiodce_idx` (`QuarterID` ASC) VISIBLE,
  CONSTRAINT `cfidroutputcomponent`
    FOREIGN KEY (`CFID`)
    REFERENCES `idr_db`.`ComponentFund` (`CFID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `quarteridoutputcomponent`
    FOREIGN KEY (`QuarterID`)
    REFERENCES `idr_db`.`Quarter` (`QuarterID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
